### PR TITLE
WIP: Berlin 2023 recap

### PR DESCRIPTION
**Pull request by mathias-brandewinder**
- [x] missing group picture
- [ ] missing correct Category
- [x] review links in footer / signature
- [ ] are there other examples of contributions?

### CODE REVIEW

**Comment by bvenn** [comment]
I've checked some other packages but couldn't find any contribution time line similar to Stats.

If Beth already got all talk slides, we could add them to [this repository](https://github.com/fslaborg/conference-resources/tree/main) and then promote/distribute the collection. But I agree, we should focus on getting the blog post finished soon. I'm happy with the github link to my profile. 

@kMutagene I think for you it should be easy to solve the category issue, right?

**Comment by kMutagene** [comment]
> I think for you it should be easy to solve the category issue, right?

What would be ideal for this? `General` ? `Announcements`?

**Comment by bvenn** [comment]
> What would be ideal for this? General ? Announcements?

Announcements :+1:

**Comment by kMutagene** [comment]
i pushed the addition of the category directly to this branch @mathias-brandewinder @bvenn. note that you can use any string for category, if it does not match our preset categories it will not have a description though, so adding a new one here made sense.

**Pull request merged**
